export default {
    mid: '1',
    direction: 'row',
    injected: null,
    selected: false,
    width: '100%',
    height: 'auto',
    margin: '',
    padding: '',
    background: '',
    children: [{
        mid: '1-1',
        type: 'magic',
        direction: 'row',
        injected: null,
        selected: false,
        width: '100%',
        height: 'auto',
        margin: '',
        padding: '',
        background: '',
        children: [],
    }, {
        mid: '1-2',
        type: 'magic',
        direction: 'column',
        injected: {
            type: 'tc-image',
            props: {
                imgSource: 'https://m.360buyimg.com/mobilecms/s700x280_jfs/t1/167727/16/12273/102253/6053aa7aE63df02b7/3d69eb7befd57ff0.jpg!cr_1125x449_0_166!q70.jpg.dpg',
            },
        },
        selected: false,
        width: '100%',
        height: 'auto',
        margin: '',
        padding: '',
        background: '',
        children: [],
    }]
};
